# Generated by Django 4.2.6 on 2024-06-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name_plural': 'School classes'},
        ),
    ]
