# Generated by Django 4.2.6 on 2024-06-16 07:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0002_alter_schoolclass_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeachersSubjects',
            new_name='TeacherSubject',
        ),
    ]
