# Generated by Django 4.2.6 on 2024-01-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
