# Generated by Django 5.1.2 on 2024-10-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=2048)),
            ],
            options={
                'verbose_name_plural': 'Diary records',
            },
        ),
    ]
