# Generated by Django 4.2.6 on 2024-01-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_letter_class_user_num_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'News'},
        ),
    ]
