# Generated by Django 4.2.6 on 2024-06-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_name_alter_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='letter_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num_class',
        ),
    ]
